####################################
# RZ/G2L SBC boards configurations
####################################

[rzg2l-sbc]
ethernet = ["11c20000", "11c30000"]

# Uload bootloader
flash_address = ["00000", "1D200", "1C700"]
load_address = "0x48000000"

# Bootloader flash SPI
[rzg2l-sbc.qspi]
BL2 = ["11E00", "00000"]
FIP = ["00000", "1D200"]
BID = ["00810", "1C700"]

# Bootloader flash eMMC
[rzg2l-sbc.emmc]
BL2 = ["1", "1", "11E00"]
FIP = ["1", "100", "00000", "2", "8"]
BID = ["1", "200", "1C700", "250", "122"]

####################################
# RZ/G2L EVK boards configurations
####################################

[rzg2l-evk]
ethernet = ["11c20000", "11c30000"]

# Uload bootloader
flash_address = ["00000", "1D200", "1C700"]
load_address = "0x48000000"

# Bootloader flash SPI
[rzg2l-evk.qspi]
BL2 = ["11E00", "00000"]
FIP = ["00000", "1D200"]
BID = ["00810", "1C700"]

# Bootloader flash eMMC
[rzg2l-evk.emmc]
BL2 = ["1", "1", "11E00"]
FIP = ["1", "100", "00000", "2", "8"]
BID = ["1", "200", "1C700", "250", "122"]

####################################
# RZ/V2L EVK boards configurations
####################################

[rzv2l-evk]
ethernet = ["11c20000", "11c30000"]

# Uload bootloader
flash_address = ["00000", "1D200", "1C700"]
load_address = "0x48000000"

# Bootloader flash SPI
[rzv2l-evk.qspi]
BL2 = ["11E00", "00000"]
FIP = ["00000", "1D200"]
BID = ["00810", "1C700"]

# Bootloader flash eMMC
[rzv2l-evk.emmc]
BL2 = ["1", "1", "11E00"]
FIP = ["1", "100", "00000", "2", "8"]
BID = ["1", "200", "1C700", "250", "122"]

####################################
# RZ/V2H EVK boards configurations
####################################

[rzv2h-evk]
ethernet = ["15c30000", "15c40000"]

# Uload bootloader
flash_address = ["00000", "60000", "120000"]
load_address = "0x48000000"

# Bootloader flash SPI
[rzv2h-evk.qspi]
BL2 = ["8101E00", "00000"]
FIP = ["00000", "60000"]
BID = ["00000", "120000"]

# Bootloader flash eMMC
[rzv2h-evk.emmc]
BL2 = ["1", "1", "8101E00"]
FIP = ["1", "100", "00000", "2", "8"]
BID = ["1", "200", "120000", "762", "762"]
